vb.organization=00000000000000000000000000000000
logging.level.org.springframework.security: INFO
manager.name=VBONE
#spring.data.mongodb.uri=mongodb://djvbadmin:KdDmNW5EsGmKJJBkFDNaKVY0uTLUoKfV@ds139567.mlab.com:39567/djvbtest
