#spring.data.mongodb.uri=mongodb://heroku:xGkqRmT6a93j3m537e4SP4MKzY53oNfogTIdpBoRtujWLr5R7VllDVqujCIpVGPusgwmMq17XzDboAWlNXyaMQ@linus.mongohq.com:10033/app11462175
#spring.data.mongodb.uri=mongodb://djvbadmin:KdDmNW5EsGmKJJBkFDNaKVY0uTLUoKfV@ds050559.mlab.com:50559/djvb
spring.data.mongodb.uri=mongodb://djvbadmin:KdDmNW5EsGmKJJBkFDNaKVY0uTLUoKfV@ds139567.mlab.com:39567/djvbtest
digits.consumer.key=Z0aFJy5A3kpsgcazoffu2sP1f
vb.organization=
manager.name=VOXBOXTWO
spring.redis.host=104.236.134.94
spring.redis.password=p1k8jo035l2ma0epqo61ovepasd
spring.redis.port=6379
security.basic.enabled: false
default.language:English
server.session.timeout=31557600
server.compression.enabled=true
server.compression.mime-types=application/javascript,application/json,application/xml,text/html,text/xml,text/plain,text/css,application/x-font-truetype