spring.data.mongodb.uri=mongodb://heroku_8h240n7d:sv9rm2p34pv7cukpmpestcv23d@ds029803.mongolab.com:29803/heroku_8h240n7d
digits.consumer.key=Z0aFJy5A3kpsgcazoffu2sP1f
vb.organization=
spring.redis.host=104.236.134.94
spring.redis.password=p1k8jo035l2ma0epqo61ovepasd
spring.redis.port=6379
