spring.data.mongodb.uri=${MONGO_URI}
spring.data.redis.host=${REDIS_HOST:redis}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.password=${REDIS_PASSWORD:}
spring.cache.type=redis
vb.organization=${VB_ORGANIZATION}
manager.name=${MANAGER_NAME}
default.language=${DEFAULT_LANGUAGE:English}
digits.consumer.key=${DIGITS_CONSUMER_KEY:}
security.basic.enabled=false
server.session.timeout=${SERVER_SESSION_TIMEOUT:31557600}
server.compression.enabled=true
server.compression.mime-types=application/javascript,application/json,application/xml,text/html,text/xml,text/plain,text/css,application/x-font-truetype,image/jpeg
management.endpoints.web.exposure.include=health
management.endpoint.health.probes.enabled=true
